name: iOS Build and Deploy
on:
  push:
    branches: [ main ]  # adjust this to your main branch name

jobs:
  build:
    name: Build and Deploy iOS
    runs-on: macos-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npx expo install --check || true

      - name: Generate iOS files
        run: |
          npx expo prebuild -p ios

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
          bundler-cache: true

      - name: Install CocoaPods
        working-directory: ios
        run: pod install

      - name: Set up code signing
        uses: apple-actions/import-codesign-certs@v2
        with: 
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}

      - name: Configure App Store Connect API
        env:
          APPSTORE_API_KEY_CONTENTS: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APPSTORE_API_KEY_CONTENTS" > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8

      - name: Build & Upload to TestFlight
        env:
          EXPO_APPLE_ID: ${{ secrets.EXPO_APPLE_ID }}
          EXPO_APPLE_PASSWORD: ${{ secrets.EXPO_APPLE_PASSWORD }}
        run: |
          xcodebuild -workspace ios/weavebe.xcworkspace \
            -scheme weavebe \
            -configuration Release \
            -archivePath $PWD/build/weavebe.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=RW5BVGDRL5 \
            PROVISIONING_PROFILE_SPECIFIER="Xcode Managed Profile" \            
            archive
          
          xcodebuild -exportArchive \
            -archivePath $PWD/build/weavebe.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $PWD/build \
            -allowProvisioningUpdates
          
          xcrun altool --upload-app --type ios \
            --file "$PWD/build/weavebe.ipa" \
            --apiKey "${{ secrets.APPSTORE_API_KEY_ID }}" \
            --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
            --verbose